---
- name: install packages
  openbsd_pkg:
    name: '{{ item }}'
    state: present
  with_items:
    - postgresql-server
    - postgresql-client

- name: initialize database
  command: initdb -D /var/postgresql/data -U postgres -E UTF8 -A peer
  args:
    creates: /var/postgresql/data/PG_VERSION
  become_user: _postgresql

- name: generate configuration
  template:
    src: postgresql.conf.j2
    dest: /var/postgresql/data/postgresql.conf
    owner: _postgresql
    group: _postgresql
    mode: 0600
  notify: restart postgresql

- name: generate pg_hba.conf
  template:
    src: '{{ item }}.j2'
    dest: /var/postgresql/data/{{ item }}
    owner: _postgresql
    group: _postgresql
    mode: 0600
  with_items:
    - pg_hba.conf
    - pg_ident.conf
  notify: reload postgresql

- name: enabled and start daemon
  service:
    name: postgresql
    enabled: yes
    state: started
